routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Post;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->name('home');

Route::get('/check', function(){
    return view('layout.base');
});

/*
Route::get('/posts', "PostsController@index");
Route::get('/posts/create' , "PostsController@create");
Route::get('/posts/{post}', "PostsController@show")->name('post.show');
Route::post('/posts', "PostsController@store");
Route::get('/posts/{post}/edit', "PostsController@edit");
Route::put('/posts/{post}', "PostsController@update");
Route::delete('/posts/{post}', "PostsController@destroy");
*/

Route::resource('posts', "PostsController");

Route::resource("products", "ProductsController");

Route::get('/sign-up', "UsersController@signUp");
Route::post('/sign-up', "UsersController@store");



Route::delete('/logout', "LoginController@destroy");
Route::get('/sign-in', "LoginController@create")->name('login');
Route::post('/sign-in', "LoginController@store");

Route::post('/comment', "CommentController@store");


Route::get('/products', "ProductController@index");
Route::get('/cart', "CartController@index");
Route::post('/cart/{product}', "CartController@store");

Route::middleware('auth')->group(function(){
    Route::get('/order', "OrderController@create");
    Route::post('/order', 'OrderController@store');
});



Route::prefix('admin')->middleware('admin')->group(function(){
    Route::get('dashboard', 'Admin\DashboardController@index');
    Route::get('secret', 'Admin\DashboardController@secret');

    Route::resource('order', 'Admin\OrderController');
});

app/Order.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Order extends Model
{
    protected $fillable = ['user_id', 'comment'];

    public function user(){
        return $this->belongsTo(User::class);
    }

    public function products(){
        return $this->belongsToMany(Product::class)
            ->withPivot('amount')->withTimestamps();
    }

}

app/Http/Controllers/Admin/OrderController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Order;
use Illuminate\Http\Request;

class OrderController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $orders = Order::all();
        return view('admin.orders.index', compact('orders'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }


    public function show(Order $order)
    {
        return view('admin.orders.show', compact('order'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/OrderController.php
<?php

namespace App\Http\Controllers;

use App\Cart;
use App\Order;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Auth;

class OrderController extends Controller
{


    public function create(){
        $cart = Cart::getCartWithProducts();

        return view('order.create', compact('cart'));
    }

    public function store(Request $request){

        DB::beginTransaction();

        try {
            $order = Order::create([
                'comment' => $request->comment,
                'user_id' => Auth::user()->id
            ]);
        }catch (\Exception $exception){
            DB::rollBack();
            return back()->withErrors(['order'=>'order wasn\'t created']);
        }
        $cart = Cart::getCartWithProducts();
        foreach ($cart as $productArr){
            try {
                $order->products()->attach($productArr['product']->id, ['amount' => $productArr['amount']]);
                $productArr['product']->decreaseStocks($productArr['amount']);
            }catch (\Exception $exception){
                DB::rollBack();
                return back()->withErrors(['product'=>'Product can\'t be added']);
            }
        }
        DB::commit();




//        return redirect('/products')->withCookie('cart', null);
    }
}

resources/views/admin/orders/index.blade.php
@extends('layout.base')

@section('jumbotron')
    <h1>Orders:</h1>
@endsection

@section('content')
    <div class="col-md-12">
        <table class="table">
            <tr>
                <th>ID</th>
                <th>User name</th>
                <th>Comment</th>
                <th></th>
            </tr>

            @forelse($orders as $order)
                <tr>
                    <th>{{$order->id}}</th>
                    <th>{{$order->user->name}}</th>
                    <th>{{$order->comment}}</th>
                    <th>
                        <a class="btn btn-warning" href="{{route('order.show', $order->id)}}">View</a>
                    </th>
                </tr>
            @empty

            @endforelse
        </table>
    </div>
@endsection

resources/views/admin/orders/show.blade.php
@extends('layout.base')

@section('jumbotron')
    <h1>Order {{$order->id}}:</h1>
@endsection

@section('content')
    <div class="col-md-12">
        <div class="row">
            <div class="col-md-4">
                <ul>
                    <li>User name: {{$order->user->name}}  </li>
                    <li>Order Id: {{$order->id}}  </li>
                    <li>Comment: {{$order->comment}}  </li>
                </ul>
            </div>
            <div class="col-md-8">
                <table class="table">
                    <tr>
                        <th>ID</th>
                        <th>Product title</th>
                        <th>Price</th>
                        <th>Amount</th>
                        <th>Total</th>
                    </tr>

                    @forelse($order->products as $product)
                        <tr>
                            <th>{{ $product->id}}</th>
                            <th>{{ $product->title}}</th>
                            <th>{{ $product->price}}</th>
                            <th>{{ $product->pivot->amount}}</th>
                            <th>{{ $product->countTotal()}}</th>
                        </tr>
                    @empty

                    @endforelse
                </table>
            </div>
        </div>
    </div>
@endsection